### ISSUE TITLE
Invalid hyperlink

### ISSUE THREAD

**Issue by FawnCobra** [MasterOfCubesAU/MOCBOT#72]
The readme file references a file call config.template.yml and when accessing the hyperlink returns a 404 as the file in no long in the master branch

https://github.com/MasterOfCubesAU/MOCBOT/blob/7ea0a9f039eb66dd56cc6cdc444223cced31159b/README.md?plain=1#L61

**Comment by MasterOfCubesAU** [comment]
Hi @FawnCobra. Thanks for the issue. It appears that the config was removed in commit https://github.com/MasterOfCubesAU/MOCBOT/commit/3f9e6244c21fb9d68f79e9d1ecdf89562e679a57 while a merge conflict was being resolved. The config template has now been re-added in https://github.com/MasterOfCubesAU/MOCBOT/commit/7ba93cd64a53d36d6464f80a9726a889ebc4ee72
